configVersion = 1

[torchconfig]
	#Use Colored Lighting on Torches with RGBLib installed
	coloredlight = true
	#Must torches be lit when placed
	litonplaced = false

[laternconfig]
	#Use Colored Lighting on Lanterns with RGBLib installed
	coloredlight = true
	#Must lanterns be lit when placed
	litonplaced = false

[tikiconfig]
	#Use Colored Lighting on Tiki Torches with RGBLib installed
	coloredlight = true
	#Must Tiki Torches be lit when placed
	litonplaced = false

[candleconfig]
	#Use Colored Lighting on Candles with RGBLib installed
	coloredlight = true
	#Must candles be lit when placed
	litonplaced = false

[redstoneconfig]
	#Use Colored Lighting on Redstone Lamps with RGBLib installed
	coloredlight = true

[batteryconfig]
	#Use Colored Lighting on Battery Neon with RGBLib installed
	coloredlight = true
	#Must battery neon be lit when placed
	litonplaced = false

[campfireconfig]
	#Use Colored Lighting on Campfires with RGBLib installed
	coloredlight = true
	#Must Campfires be lit when placed
	litonplaced = false

[jackconfig]
	#Use Colored Lighting on Jack O Lanterns with RGBLib installed
	coloredlight = true
	#Must Jack O Lanterns be lit when placed
	litonplaced = false

[soulfireconfig]
	#Use Colored Lighting on Underwater Lights with RGBLib installed
	coloredlight = true
	#Must Underwater Lights be lit when placed
	litonplaced = false

[worldgen]
	#Must colored water lakes be generated
	genColoredLakes = true
	#Must glowing colored water lakes be generated
	genColoredGlowingLakes = true

