# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = ["the_aether", "Saving block-graph for", "Registered painting", "Rerached side issue when loading REI plugin by", "is deprecated and will be removed in a future version of", "Ambiguity between arguments", "Couldn't parse data file genesis", "Couldn't parse loot table extended_drawers"]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX: 
regex = []