
["vein mining"]
	#Whether or not to vein mine diagonally, note this may lead to hidden drops if relocateDrops is false
	diagonalMining = true
	#Whether or not the tool can break while mining additional blocks
	preventToolDestruction = true
	#Whether the blocks configuration is a whitelist or a blacklist
	#Allowed Values: BLACKLIST, WHITELIST
	blocksPermission = "BLACKLIST"
	#The maximum distance from the source block per level of the enchantment
	#Range: 1 ~ 100
	maxDistancePerLevel = 6
	#Whether or not to stop vein mining when the tool can no longer be used
	limitedByDurability = true
	#List of whitelisted/blacklisted blocks or block tags
	blocks = ["agape_space:fluid_pipe", "agape_space:wire", "agape_space:copper_wire", "agape_space:gold_wire", "agape_space:fluid_tank", "techreborn:insulated_copper_cable", "techreborn:insulated_gold_cable", "techreborn:insulated_hv_cable", "techreborn:hv_cable", "techreborn:tin_cable", "techreborn:copper_cable", "techreborn:gold_cable", "techreborn:glassfiber_cable", "techreborn:superconductor_cable", "minecraft:chest", "kibe:tank", "kibe:entangled_tank", "indrev:item_pipe_mk1", "indrev:item_pipe_mk2", "indrev:item_pipe_mk3", "indrev:item_pipe_mk4", "indrev:cable_mk1", "indrev:cable_mk2", "indrev:cable_mk3", "indrev:cable_mk4", "modern_industrialization:pipe", "moderndynamics:fluid_pipe", "moderndynamics:item_pipe", "toms_storage:ts.inventory_cable", "toms_storage:ts.inventory_cable_framed", "toms_storage:ts.inventory_cable_connector", "toms_storage:ts.inventory_cable_connector_filtered", "toms_storage:ts.inventory_proxy", "toms_storage:ts.crafting_terminal", "toms_storage:ts.hopper_basic", "toms_storage:ts.level_emitter", "toms_storage:ts.painted_trim", "toms_storage:ts.trim", "toms_storage:ts.open_crate", "toms_storage:ts.storage_terminal", "toms_storage:ts.inventory_connector", "toms_storage:ts.wireless_terminal", "adorn:trading_station"]
	#The maximum number of blocks to mine without the enchantment
	#Range: 0 ~ 1000
	maxBlocksBase = 0
	#The multiplier to tool damage from mining additional blocks
	#Range: 0 ~ 1000
	toolDamageMultiplier = 7
	#Whether or not to move all drops to the same location
	relocateDrops = true
	#Whether or not the tool takes damage from mining additional blocks
	addToolDamage = true
	#The maximum distance from the source block without the enchantment
	#Range: 0 ~ 1000
	maxDistanceBase = 0
	#Whether or not to require an effective tool to vein mine blocks
	requireEffectiveTool = true
	#The multiplier to player exhaustion from mining additional blocks
	#Range: 0.0 ~ 1000.0
	playerExhaustionMultiplier = 120.0
	#The maximum number of blocks to mine per level of the enchantment
	#Range: 1 ~ 1000
	maxBlocksPerLevel = 19
	#Whether or not the player gets exhaustion from mining additional blocks
	addPlayerExhaustion = true

[groups]
	#List of groupings by block IDs or block tags, comma-separated
	groups = ["#c:adamantite_ores", "#c:aetherium_ores", "#c:aluminum_ores", "#c:amethyst_ores", "#c:antimony_ores", "#c:aquarium_ores", "#c:asterite_ores", "#c:banglum_ores", "#c:bauxite_ores", "#c:carmot_ores", "#c:certus_quartz_ores", "#c:cinnabar_ores", "#c:coal_ores", "#c:cobalt_ores", "#c:copper_ores", "#c:diamond_ores", "#c:emerald_ores", "#c:galaxium_ores", "#c:galena_ores", "#c:gold_ores,#minecraft:gold_ores", "#c:iridium_ores", "#c:iron_ores", "#c:kyber_ores", "#c:lapis_ores", "#c:lead_ores", "#c:lunum_ores", "#c:lutetium_ores", "#c:manganese_ores", "#c:metite_ores", "#c:mythril_ores", "#c:nickel_ores", "#c:orichalcum_ores", "#c:osmium_ores", "#c:palladium_ores", "#c:peridot_ores", "#c:platinum_ores", "#c:prometheum_ores", "#c:pyrite_ores", "#c:quadrillum_ores", "#c:quartz_ores", "#c:redstone_ores", "#c:ruby_ores", "#c:runite_ores", "#c:salt_ores", "#c:sapphire_ores", "#c:sheldonite_ores", "#c:silver_ores", "#c:sodalite_ores", "#c:sphalerite_ores", "#c:starrite_ores", "#c:stellum_ores", "#c:stormyx_ores", "#c:sulfur_ores", "#c:tantalite_ores", "#c:tin_ores", "#c:titanium_ores", "#c:topaz_ores", "#c:truesilver_ores", "#c:tungsten_ores", "#c:unobtainium_ores", "#c:ur_ores", "#c:uranium_ores", "#c:vermiculite_ores", "#c:zinc_ores"]

