[graveSettings]
generateGraves = true
retrievalType = "ON_USE"
dropType = "IN_INVENTORY"
dropPlayerHead = false
dropGraveBlock = false
requireGraveItem = false
generateEmptyGraves = false
ignoreSpawnProtection = true
deathInSpawnProtection = "CREATE_GRAVE"
priority = "GRAVE"
unlockableGraves = true
deleteEnchantments = ["minecraft:vanishing_curse"]
soulboundEnchantments = ["yigd:soulbound"]
loseSoulboundLevelOnDeath = false
voidSlots = []
soulboundSlots = []
applyBindingCurse = true
trySoft = false
trySoftApproach = "RADIUS"
tryStrict = true
replaceWhenClaimed = false
persistGraves = false
blacklistDimensions = []
graveInVoid = true
ignoreDeathTypes = []
graveSpawnHeight = 2
lastResort = "DROP_ITEMS"
putXpInGrave = true
defaultXpDrop = false
xpDropPercent = 80
tellDeathPos = true
maxGraveBackups = 20

[graveSettings.graveRobbing]
enableRobbing = true
onlyMurderer = false
afterTime = 40
timeType = "HOURS"
robPriority = "INVENTORY"
tellRobber = true
notifyWhenRobbed = true

[graveSettings.graveDeletion]
canDelete = true
afterTime = 48
timeType = "HOURS"
dropInventory = true

[graveSettings.itemLoss]
enableLoss = false
ignoreSoulboundItems = true
affectStacks = false
usePercentRange = false
lossRangeFrom = 0
lossRangeTo = 5
percentChanceOfLoss = 100

[graveSettings.blockUnderGrave]
generateBlockUnder = true
inOverWorld = "minecraft:cobblestone"
inNether = "minecraft:soul_soil"
inTheEnd = "minecraft:end_stone"
inCustom = "minecraft:dirt"

[graveSettings.graveCompatConfig]
levelzXpInGraves = false
levelzXpDropPercent = 100
claimRuleOverride = "CREATE_GRAVE"
prioritiseTheGraveyardGraves = false
graveyardSearchRadius = 10
keepAllTrinkets = false

[graveSettings.graveRenderSettings]
useRenderFeatures = true
useSpecialBlockRenderer = true
renderGraveSkull = true
renderGraveOwner = true
textShadow = true
adaptRenderer = false
glowingGrave = true
glowMinDistance = 0
glowMaxDistance = 14
[utilitySettings.soulboundEnchant]
enabled = true
isTreasure = false
villagerTrade = true
tableAndLoot = false
[utilitySettings.deathSightEnchant]
enabled = false
isTreasure = false
villagerTrade = false
tableAndLoot = false
[utilitySettings.scrollItem]
scrollType = "INFO_SCROLL"
retrieveOnRespawn = false
[utilitySettings.graveKeySettings]
enableKeys = false
alwaysRequire = false
retrieveOnRespawn = true
getFromGui = false
rebindable = false
graveKeySpecification = "PLAYER"
[utilitySettings.graveCompassSettings]
receiveOnDeath = false
tryDeleteOnClaim = true
[commandToggles]
coreCommandName = "yigd"
retrieveGrave = true
robGrave = true
selfView = true
adminView = true
moderateGraves = true
clearGraveBackups = true
whitelist = true
whitelistAdd = true
whitelistRemove = true
whitelistToggle = true
coordinateToggle = true
[debugConfig]
clearInventoryOnRespawn = false
createGraveBeforeDeathMessage = false
