[graveSettings]
generateGraves = true
retrievalType = "ON_USE"
compactRetrieveItems = true
retrievalRequireShovel = false
dropType = "IN_INVENTORY"
dropPlayerHead = false
dropGraveBlock = false
requireGraveItem = false
generateEmptyGraves = false
ignoreSpawnProtection = true
deathInSpawnProtection = "CREATE_GRAVE"
priority = "GRAVE"
unlockableGraves = true
deleteEnchantments = ["minecraft:vanishing_curse"]
soulboundEnchantments = ["yigd:soulbound"]
loseSoulboundLevelOnDeath = false
voidSlots = []
soulboundSlots = []
applyBindingCurse = true
useLastGroundPos = false
trySoft = false
trySoftApproach = "RADIUS"
tryStrict = true
replaceWhenClaimed = false
persistGraves = false
onDestroyedDrop = "NONE"
blacklistDimensions = []
graveInVoid = true
ignoreDeathTypes = []
graveSpawnHeight = 2
lastResort = "DROP_ITEMS"
putXpInGrave = true
defaultXpDrop = false
xpDropPercent = 80
tellDeathPos = true
maxGraveBackups = 20

[graveSettings.graveRobbing]
enableRobbing = true
onlyMurderer = false
afterTime = 40
timeType = "HOURS"
robPriority = "INVENTORY"
tellRobber = true
notifyWhenRobbed = true

[graveSettings.graveDeletion]
canDelete = true
afterTime = 48
timeType = "HOURS"
dropInventory = true

[graveSettings.itemLoss]
enableLoss = false
ignoreSoulboundItems = true
affectStacks = false
usePercentRange = false
lossRangeFrom = 0
lossRangeTo = 5
percentChanceOfLoss = 100

[graveSettings.randomSpawnSettings]
percentSpawnChance = 0
spawnEntity = "minecraft:zombie"
spawnNbt = "{ArmorItems:[{},{},{},{id:\"minecraft:player_head\",tag:{SkullOwner:{Name:\"${name}\",Id:\"${uuid}\"}},Count:1b}]}"

[graveSettings.blockUnderGrave]
generateBlockUnder = true
inOverWorld = "minecraft:cobblestone"
inNether = "minecraft:soul_soil"
inTheEnd = "minecraft:end_stone"
inCustom = "minecraft:dirt"
generateWhenProtected = false

[graveSettings.graveCompatConfig]
levelzXpInGraves = false
levelzXpDropPercent = 100
claimRuleOverride = "CREATE_GRAVE"
prioritiseTheGraveyardGraves = false
graveyardSearchRadius = 10
keepAllTrinkets = false

[graveSettings.graveRenderSettings]
useRenderFeatures = true
useSpecialBlockRenderer = true
renderGraveSkull = true
renderGraveOwner = true
textShadow = true
adaptRenderer = false
glowingGrave = true
glowMinDistance = 0
glowMaxDistance = 14

[graveSettings.graveRenderSettings.guiTextColors]
graveSelectGraveLocation = 13369548
graveSelectItemSize = 204
graveSelectLevelSize = 2725384
graveSelectTitle = 5592405
graveSelectPageView = 30464
graveSelectShowAvailableCheckbox = 7829367
graveSelectShowClaimedCheckbox = 7829367
graveSelectShowDestroyedCheckbox = 7829367
graveSelectShowStatusCheckbox = 7829367
graveViewLockGrave = 0
graveViewUnlockGrave = 0
graveViewRestoreGrave = 0
graveViewDeleteGrave = 0
graveViewRobGrave = 0
graveViewGiveKey = 0
graveViewDeathMessage = 11141120
graveViewDeathDimension = 21956
graveViewCoordinates = 12255419
graveViewModItemSize = 5592405
graveViewLevelSize = 2725384
claimedBy = 0
playerSelectPlayerName = 16384
playerSelectGraveCount = 5592405
playerSelectTitle = 5592405
playerSelectPageView = 30464
playerSelectIncludeAvailableCheckbox = 7829367
playerSelectIncludeClaimedCheckbox = 7829367
playerSelectIncludeDestroyedCheckbox = 7829367
playerSelectShowZeroCheckbox = 7829367
playerSelectSearchBar = 16777215
[utilitySettings.soulboundEnchant]
enabled = true
isTreasure = false
villagerTrade = true
tableAndLoot = false
[utilitySettings.deathSightEnchant]
enabled = false
isTreasure = false
villagerTrade = false
tableAndLoot = false
[utilitySettings.scrollItem]
scrollType = "INFO_SCROLL"
retrieveOnRespawn = false
[utilitySettings.graveKeySettings]
enableKeys = false
alwaysRequire = false
retrieveOnRespawn = true
getFromGui = false
rebindable = false
graveKeySpecification = "PLAYER"
[utilitySettings.graveCompassSettings]
receiveOnDeath = false
tryDeleteOnClaim = true
[commandToggles]
coreCommandName = "yigd"
retrieveGrave = true
robGrave = true
selfView = true
adminView = true
moderateGraves = true
clearGraveBackups = true
whitelist = true
whitelistAdd = true
whitelistRemove = true
whitelistToggle = true
coordinateToggle = true
[debugConfig]
clearInventoryOnRespawn = false
createGraveBeforeDeathMessage = false
