on: [push]

jobs:
  disord_test_message:
    runs-on: ubuntu-latest
    name: discord commits
    steps:
        - name: Discord Commits
          uses: ./
          with:
                webhook: ${{ secrets.DISCORD_WEBHOOK }}
                message: "Successful commit to **{{ github.context.payload.repository.owner.name }}/{{ github.context.payload.repository.name}}**.\nDiff: {{ github.context.payload.compare }}"
                embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars.io/gravatar/{{ commit.author.email }}"} }'
                last-commit-only: false
